alertmanager:
  config:
    global:
      resolve_timeout: 5m
      smtp_smarthost: "smtp.gmail.com:587"
      smtp_from: "nguyenzika117@gmail.com"
      smtp_auth_username: "nguyenzika117@gmail.com"
      smtp_auth_password: "lhzh ssud nfhc pemh"
      smtp_require_tls: true

    route:
      # Default receiver (will receive all alerts)
      receiver: "email-receiver"
      group_wait: 5s
      group_interval: 10s
      repeat_interval: 1h

      # Routes section
      routes:
        - match:
            severity: critical
          receiver: "webhook-receiver"
          group_wait: 0s

    receivers:
      - name: "null"

      - name: "webhook-receiver"
        webhook_configs:
          - url: "http://host.docker.internal:3000/webhook"
            send_resolved: true

      - name: "email-receiver"
        email_configs:
          - to: "nguyenzika117@gmail.com"
            send_resolved: true
            html: |
              {{ range .Alerts }}
                <h3>[{{ .Status | toUpper }}] {{ .Labels.alertname }}</h3>
                <p><strong>Mức độ:</strong> {{ .Labels.severity }}</p>
                <p><strong>Bắt đầu:</strong> {{ .StartsAt }}</p>
                {{ if .Annotations.description }}
                <p>{{ .Annotations.description }}</p>
                {{ end }}
                <hr/>
              {{ end }}
