alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      receiver: custom-webhook
      group_wait: 5s
      group_interval: 10s
      repeat_interval: 1h
    receivers:
      - name: "null"
      - name: custom-webhook
        webhook_configs:
          - url: http://host.docker.internal:3000/webhook
            send_resolved: true
